// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHhU8WG5MMIRJCH21BYMQ4TbvFFsp8ypg',
    appId: '1:720891965669:web:ffb1c19fc1d5659fd6a40c',
    messagingSenderId: '720891965669',
    projectId: 'careasenew-7ee37',
    authDomain: 'careasenew-7ee37.firebaseapp.com',
    storageBucket: 'careasenew-7ee37.firebasestorage.app',
    measurementId: 'G-GL8RBL7PP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdYigWPcGqVyz8XM8VfKxHYKkB7F-lGF8',
    appId: '1:720891965669:android:aeff3867d5d7a3e5d6a40c',
    messagingSenderId: '720891965669',
    projectId: 'careasenew-7ee37',
    storageBucket: 'careasenew-7ee37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeM7qcEvuN4JU8FDgNL-Z9uQIk7ttjuiI',
    appId: '1:720891965669:ios:0ba2815a55c0e2c9d6a40c',
    messagingSenderId: '720891965669',
    projectId: 'careasenew-7ee37',
    storageBucket: 'careasenew-7ee37.firebasestorage.app',
    iosBundleId: 'com.example.careasen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeM7qcEvuN4JU8FDgNL-Z9uQIk7ttjuiI',
    appId: '1:720891965669:ios:0ba2815a55c0e2c9d6a40c',
    messagingSenderId: '720891965669',
    projectId: 'careasenew-7ee37',
    storageBucket: 'careasenew-7ee37.firebasestorage.app',
    iosBundleId: 'com.example.careasen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHhU8WG5MMIRJCH21BYMQ4TbvFFsp8ypg',
    appId: '1:720891965669:web:55b582680adc88bdd6a40c',
    messagingSenderId: '720891965669',
    projectId: 'careasenew-7ee37',
    authDomain: 'careasenew-7ee37.firebaseapp.com',
    storageBucket: 'careasenew-7ee37.firebasestorage.app',
    measurementId: 'G-PLVFNEV9HD',
  );

}